package com.xinrong.system.student_information_system.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Boards")
public class Board extends DynamoDBObject {

	private String id;

	private long boardId;
	private long courseId;

	public Board() {

	}

	public Board(long boardId, long courseId) {
		this.boardId = boardId;
		this.courseId = courseId;
	}

	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBHashKey(attributeName = "BoardId")
	public long getBoardId() {
		return boardId;
	}

	public void setBoardId(long boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute(attributeName = "CourseId")
	@DynamoDBIndexHashKey(attributeName = "CourseId", globalSecondaryIndexName = "CourseIdInBoard")
	public long getCourseId() {
		return courseId;
	}

	public void setCourseId(long courseId) {
		this.courseId = courseId;
	}

}
