package com.xinrong.system.student_information_system.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Registrar")
public class Registrar extends DynamoDBObject {
	private String id;
	
	private long registrationId;
	private long offeringId;
	private String offeringType;
	private String department;
	private int perUnitPrice;
	
	public Registrar() {
		
	}
	
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBHashKey(attributeName = "RegistrationId")
	public long getRegistrationId() {
		return registrationId;
	}
	public void setRegistrationId(long registrationId) {
		this.registrationId = registrationId;
	}
	
	@DynamoDBAttribute(attributeName = "OfferingId")
	public long getOfferingId() {
		return offeringId;
	}
	public void setOfferingId(long offeringId) {
		this.offeringId = offeringId;
	}
	
	@DynamoDBAttribute(attributeName = "OfferingType")
	public String getOfferingType() {
		return offeringType;
	}
	public void setOfferingType(String offeringType) {
		this.offeringType = offeringType;
	}
	
	@DynamoDBAttribute(attributeName = "Department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	
	@DynamoDBAttribute(attributeName = "PerUnitPrice")
	public int getPerUnitPrice() {
		return perUnitPrice;
	}
	public void setPerUnitPrice(int perUnitPrice) {
		this.perUnitPrice = perUnitPrice;
	}
	
	
}